### ISSUE TITLE
diffrent stripe width

### ISSUE THREAD

**Issue by Samy-Nagy** [Abdul-Moiz/AMProgressBar#1]
i want to make different stripe width... how?

**Comment by Abdul-Moiz** [comment]
Just set in the global configs.
`AMProgressBar.config.stripesWidth = 30`
or for specific progress bar
`progressBar.customize { bar in
    bar.stripesWidth = 10
}`

**Comment by SamiYousef** [comment]
![screen shot 2017-12-11 at 6 15 07 pm](https://user-images.githubusercontent.com/13000537/33841078-57eb7486-de9f-11e7-8b1b-50b2685968d2.png)
i want to make progress like this

**Comment by SamiYousef** [comment]
the yellow stripe width not equal black stripe width

**Comment by Abdul-Moiz** [comment]
This feature is now added. 
you can use **progressBar.stripesSpacing** to control it.
