### ISSUE TITLE
stop progress

### ISSUE THREAD

**Issue by Samy-Nagy** [Abdul-Moiz/AMProgressBar#4]
imagine i want to move from (a)--->(b) in period of time and wanted to stop progress before reaching the max value (b).
how can i do this?

**Comment by Abdul-Moiz** [comment]
You need to use `setProgress(progress: CGFloat, animated: Bool)` method to reach certain point.
Progress range is 0-1 so you need to provide it with `current_progress/max_value` and it will animate to that point.

**Comment by Samy-Nagy** [comment]
i wanted to stop progress according to user action 
so i added this method to pause animation 
func stopAnimation() {
        guard let barLayer = barLayer else { return }
        let pausedTime = barLayer.convertTime(CACurrentMediaTime(), from: nil)
        barLayer.speed = 0.0
        barLayer.timeOffset = pausedTime
    }
thanks :)
